export const BranchList: string[] = [
    "No Filter",
    "All Branches",
    "Automobile",
    "Aeronautical",
    "Biomedical",
    "Biotechnology",
    "Chemical",
    "Civil",
    "Computer & Communication Engineering",
    "Computer Science & Engineering",
    "Computer Science & Engineering - AI & ML",
    "Data Science & Engineering",
    "Electrical & Electronics Engineering",
    "Electronics & Communication Engineering",
    "Electronics & Instrumentation Engineering",
    "Industrial Production Engineering",
    "Information Technology",
    "Mechanical Engineering",
    "Mechatronics Engineering",
];